version: "3"
services:
  frontend:
    build:
      context: .
      restart: always
      args:
        NODE_ENV: "development"
    environment:
      - DEPLOY_ENV=${DEPLOY_ENV:-development}
    volumes:
      - .:/web
    ports:
      - ${PORT:-3000}:3000
